USE hr;

SELECT MAX(SALARY) FROM employees;

SELECT MAX(SALARY) - MIN(SALARY) FROM employees;

SELECT 
    AVG(SALARY), JOB_ID
FROM
    employees
GROUP BY SALARY , JOB_ID
ORDER BY AVG(SALARY) DESC;

SELECT SUM(SALARY) FROM employees;

SELECT 
    MAX(ROUND(SALARY, 2)),
    MIN(ROUND(SALARY, 2)),
    SUM(ROUND(SALARY, 2)),
    AVG(ROUND(SALARY, 2))
FROM
    employees;

SELECT COUNT('IT_PROG') FROM employees;

SELECT COUNT(JOB_ID), SUM(SALARY) FROM employees GROUP BY JOB_ID, SALARY;

SELECT SUM(SALARY) FROM employees WHERE JOB_ID = 'IT_PROG';

SELECT 
    JOB_ID, AVG(SALARY)
FROM
    employees
GROUP BY JOB_ID , SALARY
HAVING JOB_ID <> 'IT_PROG'
ORDER BY AVG(SALARY) DESC;

SELECT 
    AVG(SALARY) 'average_salary', COUNT(*) 'number_of_employees'
FROM
    employees
GROUP BY DEPARTMENT_ID
HAVING `number_of_employees` > 10;

SELECT REPLACE(PHONE_NUMBER, 515, 777) FROM employees;

SELECT FIRST_NAME FROM employees WHERE CHAR_LENGTH(FIRST_NAME) >= 8; 

SELECT EMPLOYEE_ID, FIRST_NAME, YEAR(HIRE_DATE) FROM employees;

SELECT EMPLOYEE_ID, FIRST_NAME, DAY(HIRE_DATE) FROM employees;

SELECT EMPLOYEE_ID, FIRST_NAME, MONTH(HIRE_DATE) FROM employees;

SELECT UCASE(CONCAT(FIRST_NAME , ' ', LAST_NAME)) FROM employees;

SELECT LAST_NAME, HIRE_DATE, COUNT(*) FROM employees GROUP BY LAST_NAME HAVING HIRE_DATE = '1987-07-01';

SELECT 
    LAST_NAME, HIRE_DATE
FROM
  employees
WHERE MONTH(HIRE_DATE) = 7 AND YEAR(HIRE_DATE) = 1987;
